<?php

namespace app\models\christmascalendar;

use Yii;
use yii\db\Query;

/**
 * This is the model class for table "{{%christmas_calendar_question}}".
 *
 * @property int $id
 * @property int $id_user
 * @property int $day
 * @property string|null $date_create
 * @property string $photo
 * @property string $description
 *
 * @property ChristmasCalendarAnswer[] $christmasCalendarAnswers
 * @property ChristmasCalendarUsers $user
 */
class ChristmasCalendarQuestion extends \yii\db\ActiveRecord
{
    private static $pics = [
        'bell-icon.png',
        'black-peter-icon.png',
        'candle-icon.png',
        'candy-icon.png',
        'candy-stick-icon.png',
        'christmas-ball-icon.png',
        'christmas-star-icon.png',
        'christmas-tree-icon.png',
        'christmas-wrench-icon.png',
        'cookie-icon.png',
        'crystal-ball-icon.png',
        'fire-stove-icon.png',
        'mail-christmas-icon.png',
        'ribbon-icon.png',
        'rocket-icon.png',
        'rudolph-icon.png',
        'santa-bag-icon.png',
        'santa-cart-icon.png',
        'santa-claus-icon.png',
        'santa-hat-icon.png',
        'snow-flakes-icon.png',
        'snowman-icon.png',
        'sock-icon.png',
    ];


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%christmas_calendar_question}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user', 'day'], 'required'],
            [['id_user', 'day'], 'integer'],
            [['date_create'], 'safe'],
            //[['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => ChristmasCalendarUsers::className(), 'targetAttribute' => ['id_user' => 'id']],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'day' => 'Day',
            'date_create' => 'Date Create',
        ];
    }

    /**
     * Gets query for [[ChristmasCalendarAnswers]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getChristmasCalendarAnswers()
    {
        return $this->hasMany(ChristmasCalendarAnswer::className(), ['id_question' => 'id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return (new Query())
            ->from('{{%christmas_calendar_users}}')
            ->where(['id'=>$this->id_user])
            ->one();
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array|\yii\db\ActiveRecord|null
     * @throws \Exception
     */
    public static function findToday()
    {
        $model = new ChristmasCalendar();
        return $model->today();
    }


    /**
     * @return mixed
     */
    public static function pickRandom()
    {
        $rand = rand(0, count(self::$pics)-1);
        return '/images/crismas-calendar/' . self::$pics[$rand];
    }

    /**
     * @param $idQuestion
     * @param $idUser
     * @throws \yii\db\Exception
     */
    public function saveAnswer($idUser)
    {
        if (!$this->isAnswered()) {
            Yii::$app->db->createCommand()
                ->insert('{{%christmas_calendar_answer}}', [
                    'id_question' => $this->id,
                    'id_user' => $idUser,
                    'username' => Yii::$app->user->identity->username,
                ])
                ->execute();
        }
    }

    /**
     * @return bool
     */
    public function isAnswered()
    {
        return (new Query())
            ->from('{{%christmas_calendar_answer}}')
            ->where([
                'id_question' => $this->id,
                'username' => Yii::$app->user->identity->username,
            ])
            ->exists();
    }


}
