<?php
namespace tests\_data;

use \Faker;
use Yii;

$facker = Faker\Factory::create();

return [
    11 => [
        'code_org' => '8600',
        'type_conference' => 1,
        'theme' => 'Vks Ufns 1',
        'responsible' => $facker->text(200),
        'members_people' => $facker->text(500),
        'members_organization' => $facker->text(500),
        'date_start' => Yii::$app->formatter->asDateTime('2023-05-01 14:30:00'),
        'time_start_msk' => 0,
        'duration' => '01:30',
        'is_confidential' => 0,
        'place' => '101 каб.',
        'note' => $facker->text(600),
        'status' => 'complete',
        'editor' => 'system',
    ],
    12 => [
        'code_org' => '8600',
        'type_conference' => 1,
        'theme' => 'Vks Ufns 2',
        'responsible' => $facker->text(200),
        'members_people' => $facker->text(500),
        'members_organization' => $facker->text(500),
        'date_start' => Yii::$app->formatter->asDateTime('2023-05-02 10:30:00'),
        'time_start_msk' => 0,
        'duration' => '00:30',
        'is_confidential' => 1,
        'place' => '202 каб.',
        'note' => $facker->text(600),
        'status' => 'complete',
        'editor' => 'system',
    ],

    21 => [
        'code_org' => '8601',
        'type_conference' => 2,
        'theme' => 'Vks Fns 1',
        'responsible' => $facker->text(200),
        'members_people' => $facker->text(500),
        'members_organization' => $facker->text(500),
        'date_start' => Yii::$app->formatter->asDateTime('2023-05-01 12:30:00'),
        'time_start_msk' => 1,
        'duration' => '02:00',
        'is_confidential' => 0,
        'place' => '101 каб.',
        'note' => $facker->text(600),
        'status' => 'complete',
        'editor' => 'system',
    ],
    22 => [
        'code_org' => '8600',
        'type_conference' => 2,
        'theme' => 'Vks Fns 2',
        'responsible' => $facker->text(200),
        'members_people' => $facker->text(500),
        'members_organization' => $facker->text(500),
        'date_start' => Yii::$app->formatter->asDateTime('2023-05-03 10:30:00'),
        'time_start_msk' => 1,
        'duration' => '01:00',
        'is_confidential' => 0,
        'place' => '303 каб.',
        'note' => $facker->text(600),
        'status' => 'complete',
        'editor' => 'system',
    ],

    31 => [
        'code_org' => '8600',
        'type_conference' => 3,
        'theme' => 'Conference 1',
        'responsible' => $facker->text(200),
        'members_people' => $facker->text(500),
        'members_organization' => $facker->text(500),
        'date_start' => Yii::$app->formatter->asDateTime('2023-05-05 11:00:00'),
        'time_start_msk' => 0,
        'duration' => '00:30',
        'is_confidential' => 0,
        'place' => '202 каб.',
        'note' => $facker->text(600),
        'status' => 'complete',
        'editor' => 'system',
    ],
    32 => [
        'code_org' => '8600',
        'type_conference' => 3,
        'theme' => 'Conference 2',
        'responsible' => $facker->text(200),
        'members_people' => $facker->text(500),
        'members_organization' => $facker->text(500),
        'date_start' => Yii::$app->formatter->asDateTime('2023-05-03 15:30:00'),
        'time_start_msk' => 0,
        'duration' => '01:00',
        'is_confidential' => 1,
        'place' => '202 каб.',
        'note' => $facker->text(600),
        'status' => 'new',
        'editor' => 'system',
    ],

    41 => [
        'code_org' => '8603',
        'type_conference' => 4,
        'theme' => 'Vks External 1',
        'responsible' => $facker->text(200),
        'members_people' => $facker->text(500),
        'members_organization' => $facker->text(500),
        'date_start' => Yii::$app->formatter->asDateTime('2023-05-02 16:10:00'),
        'time_start_msk' => 1,
        'duration' => '01:40',
        'is_confidential' => 0,
        'place' => '303 каб.',
        'note' => $facker->text(600),
        'status' => 'complete',
        'editor' => 'system',
    ],
    42 => [
        'code_org' => '8600',
        'type_conference' => 4,
        'theme' => 'Vks External 2',
        'responsible' => $facker->text(200),
        'members_people' => $facker->text(500),
        'members_organization' => $facker->text(500),
        'date_start' => Yii::$app->formatter->asDateTime('2023-05-04 09:00:00'),
        'time_start_msk' => 1,
        'duration' => '03:00',
        'is_confidential' => 0,
        'place' => '202 каб.',
        'note' => $facker->text(600),
        'status' => 'complete',
        'editor' => 'system',
    ],

    51 => [
        'code_org' => '8600',
        'type_conference' => 5,
        'theme' => 'Vks Kontur Talk 1',
        'responsible' => $facker->text(200),
        'members_people' => $facker->text(500),
        'members_organization' => $facker->text(500),
        'date_start' => Yii::$app->formatter->asDateTime('2023-05-11 14:40:00'),
        'time_start_msk' => 1,
        'duration' => '02:20',
        'is_confidential' => 0,
        'place' => '101 каб.',
        'note' => $facker->text(600),
        'status' => 'complete',
        'editor' => 'system',
    ],
    52 => [
        'code_org' => '8602',
        'type_conference' => 5,
        'theme' => 'Vks Kontur Talk 2',
        'responsible' => $facker->text(200),
        'members_people' => $facker->text(500),
        'members_organization' => $facker->text(500),
        'date_start' => Yii::$app->formatter->asDateTime('2023-05-05 09:00:00'),
        'time_start_msk' => 1,
        'duration' => '01:30',
        'is_confidential' => 0,
        'place' => '601 каб.',
        'note' => $facker->text(600),
        'status' => 'complete',
        'editor' => 'system',
    ],

];